name: Actualizar Token Color Vision
on:
  schedule:
    - cron: '0 */3 * * *' # Se ejecuta cada 3 horas
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Instalar librerías
        run: pip install requests
      - name: Ejecutar script
        run: python actualizador.py
      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lista.m3u
          git commit -m "Lista actualizada" || exit 0
          git push
