name: Actualizar Token Color Vision

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script
        run: python actualizador.py

      - name: Guardar cambios
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lista.m3u
          git commit -m "Lista actualizada" || exit 0
          git push "https://x-access-token:${{ secrets.MY_TOKEN }}@://github.com{{ github.repository }}.git" main
